src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Serializer\Annotation\Groups;
/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"Username"},message="Username déjà existant !")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("post:read")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Type(type={"alpha", "digit"}, message="Votre nom doit contenir seulement des lettres alphabétiques")
     * @Groups("post:read")
     */

    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Type(type={"alpha", "digit"},message="Votre prénom doit contenir seulement des lettres alphabétiques" )
     * @Groups("post:read")
     */
    private $Prenom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("post:read")
     */
    private $Username;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message=" Email n'est pas valide")
     * @Groups("post:read")
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     * @Groups("post:read")
     */
    private $Roles = [];

    /**
     * @ORM\Column(type="string", length=255)
     *@Assert\Length(
     * min = 8,
     * minMessage = "Votre mot de passe doit contenir au moins 8 caracteres",
     * allowEmptyString = false)
     * @Groups("post:read")
     */
    private $Password;

    /**
     * @Assert\EqualTo(propertyPath ="Password",message="Vous n'avez pas saisi le même mot de passe." )

     */

    private $confirm_password;
    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("post:read")
     */
    private $file;
    /**
     * @ORM\Column(type="datetime")
     * @Groups("post:read")
     */
    private $Created_at;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)

     */
    private $activation_token;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\Length(
     *      min = 8,
     *      max = 8,
     *      minMessage = "Your first name must be at least {{ limit }} characters long",
     *      maxMessage = "Your first name cannot be longer than {{ limit }} characters"
     * )
     * @Groups("post:read")
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups("post:read")
     */
    private $Address;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Groups("post:read")
     */
    private $reset_token;

    /**
     * @ORM\Column(type="integer")
     * @Groups("post:read")
     */
    private $Etat=0;

    /**
     * @ORM\OneToMany(targetEntity=Reclamation::class, mappedBy="user")
     * @ORM\JoinColumn(nullable=false)
     */
    private $reclamations;



    public function __construct()
    {
        $this->reclamations = new ArrayCollection();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->Username;
    }

    public function setUsername(string $Username): self
    {
        $this->Username = $Username;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getRoles(): ?array
    {
        $roles = $this->Roles;
        $roles[] = 'ROLE_USER';
        return array_unique($roles);
    }

    public function setRoles(array $Roles): self
    {
        $this->Roles = $Roles;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->Password;
    }

    public function setPassword(string $Password): self
    {
        $this->Password = $Password;

        return $this;
    }

    public function getFile()
    {
        return $this->file;
    }

    public function setFile($file)
    {
        $this->file = $file;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getConfirmPassword()
    {
        return $this->confirm_password;
    }

    /**
     * @param mixed $confirm_password
     */
    public function setConfirmPassword($confirm_password): void
    {
        $this->confirm_password = $confirm_password;
    }
    public function eraseCredentials() {}
    public function getSalt() {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->Created_at;
    }

    public function setCreatedAt(\DateTimeInterface $Created_at): self
    {
        $this->Created_at = $Created_at;

        return $this;
    }

    public function getActivationToken(): ?string
    {
        return $this->activation_token;
    }

    public function setActivationToken(?string $activation_token): self
    {
        $this->activation_token = $activation_token;

        return $this;
    }

    public function getPhone(): ?int
    {
        return $this->phone;
    }

    public function setPhone(int $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->Address;
    }

    public function setAddress(?string $Address): self
    {
        $this->Address = $Address;

        return $this;
    }

    public function getResetToken(): ?string
    {
        return $this->reset_token;
    }

    public function setResetToken(?string $reset_token): self
    {
        $this->reset_token = $reset_token;

        return $this;
    }

    public function getEtat(): ?int
    {
        return $this->Etat;
    }

    public function setEtat(int $Etat): self
    {
        $this->Etat = $Etat;

        return $this;
    }

    /**
     * @return Collection|Reclamation[]
     */
    public function getReclamations(): Collection
    {
        return $this->reclamations;
    }

    public function addReclamation(Reclamation $reclamation): self
    {
        if (!$this->reclamations->contains($reclamation)) {
            $this->reclamations[] = $reclamation;
            $reclamation->setUser($this);
        }

        return $this;
    }

    public function removeReclamation(Reclamation $reclamation): self
    {
        if ($this->reclamations->removeElement($reclamation)) {
            // set the owning side to null (unless already changed)
            if ($reclamation->getUser() === $this) {
                $reclamation->setUser(null);
            }
        }

        return $this;
    }


}

src/Controller/FrontController.php
<?php

namespace App\Controller;

use App\Entity\Reclamation;
use App\Entity\User;
use App\Entity\Review;
use App\Form\AddReclamationType;
use App\Repository\NotificationRepository;
use App\Repository\ReclamationRepository;
use App\Repository\ReviewRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
class FrontController extends AbstractController
{
    /**
     * @Route("/", name="front")
     */
    public function index(ReviewRepository $repository): Response
    {
        $rev=$repository->findRevMax();
        return $this->render('front/homeFront.html.twig',[
            'rev'=>$rev
        ]);
    }

    /**
     * @return Response
     * @Route("/team",name="team")
     */
    public function afficherChefs(UserRepository $repository){
        $chef=$repository->findChef();
        return $this->render('/front/employes/team.html.twig',[
            'chef'=>$chef
        ]);
    }

    /**
     * @Route("/show_chef/{id}", name="show_chef")
     */
    public function afficherDetailsChef($id,UserRepository $repository){
        $chef=$repository->find($id);
        return $this->render('/front/employes/chefDetail.html.twig',[
            'chef'=>$chef
        ]);
    }

    /**
     * @param Request $request
     * @param UserRepository $repository
     * @Route("/search" , name="search")
     */
    public function search(Request $request,UserRepository $repository){
        $em = $this->getDoctrine()->getManager();

        $requestString = $request->get('q');

        $entities =$repository->findChefByValue($requestString);

        if(!$entities) {
            $result['entities']['error'] = "Aucun chef trouvé";
        } else {
            $result['entities'] = $this->getRealEntities($entities);
        }

        return new Response(json_encode($result));
    }
    public function getRealEntities($entities){

        foreach ($entities as $entity){
            $realEntities[$entity->getId()] =[ $entity->getFile(),$entity->getPrenom()];

        }
        return $realEntities;

    }

    public function showR(ReviewRepository $repository){
        $rev=$repository->findRevMax();
        return $this->render('front/homeFront.html.twig',[
            'rev'=>$rev
        ]);
    }

    /**
     * @return Response
     * @Route("showReview", name="showReview")
     */
    public function showReviews(){

        return $this->render('front/Review/show.html.twig');
    }

    /**
     * @Route("addReview" , name="addReview")
     */
    public function ajouterReview(){
        if(isset($_POST["rating_data"])){
            $Review = new Review();
            $Review->setDescription($_POST["user_review"]);
            $Review->setPublishedAt(new \DateTime('now'));
            $Review->setStars($_POST["rating_data"]);
            $Review->setUserName($_POST["user_name"]);
            $em=$this->getDoctrine()->getManager();
            $em->persist($Review);
            $em->flush();

        }
        return $this->redirectToRoute('showReview');
    }

    /**
     * @param ReviewRepository $repository
     * @return false|string
     * @Route("/calculer", name="calculer")
     */
    public function calculer(ReviewRepository $repository){
        if(isset($_POST["action"])){
            $average_rating = 0;
            $total_review = 0;
            $five_star_review = 0;
            $four_star_review = 0;
            $three_star_review = 0;
            $two_star_review = 0;
            $one_star_review = 0;
            $total_user_rating = 0;
            $review_content = array();
            $result=$repository->findDESC();

            foreach($result as $row)
            {
                $review_content[] = array(
                    'user_name'		=>	$row->getUserName(),
                    'user_review'	=>	$row->getDescription(),
                    'rating'		=>	$row->getStars(),
                    'datetime'		=>	$row->getPublishedAt()
                );

                if($row->getStars() == '5')
                {
                    $five_star_review++;
                }

                if($row->getStars() == '4')
                {
                    $four_star_review++;
                }

                if($row->getStars() == '3')
                {
                    $three_star_review++;
                }

                if($row->getStars() == '2')
                {
                    $two_star_review++;
                }

                if($row->getStars() == '1')
                {
                    $one_star_review++;
                }

                $total_review++;

                $total_user_rating = $total_user_rating + $row->getStars();

            }

            $average_rating = $total_user_rating / $total_review;

            $output = array(
                'average_rating'	=>	number_format($average_rating, 1),
                'total_review'		=>	$total_review,
                'five_star_review'	=>	$five_star_review,
                'four_star_review'	=>	$four_star_review,
                'three_star_review'	=>	$three_star_review,
                'two_star_review'	=>	$two_star_review,
                'one_star_review'	=>	$one_star_review,
                'review_data'		=>	$review_content
            );


        }
        return New Response(json_encode($output));
    }


    ///////////////////////////MOBILE/////////////////////////
    /**
     * @Route("/addRevJson" ,name="addRevJson")
     * @Method ("POST")
     */
    public function addRevJson(Request $request, NormalizerInterface $Normalizer){

        $review =new Review();
        $description = $request->get("description");
        $username= $request->get("user_name");
        $stars=$request->get("stars");

        $review->setStars($stars);
        $review->setDescription($description);
        $review->setUserName($username);
        $review->setPublishedAt(new \DateTime('now'));



        $em=$this->getDoctrine()->getManager();
        $em->persist($review);
        $em->flush();

        $jsonContent=$Normalizer->normalize($review,'json',['groups'=>'post:read']);
        return new Response('Ajout effectué avec success'.json_encode($jsonContent));
    }

    /**
     * @Route("/deleteRevJson/{id}", name="deleteRevJson")
     * @Method ("POST")
     */
    public function deleteReviewJson(Request $request,NormalizerInterface $Normalizer,$id){


        $em=$this->getDoctrine()->getManager();

        $review = $em->getRepository(Review::class)->find($id);
        if($review != null){
            $em->remove( $review);
            $em->flush();


            $jsonContent=$Normalizer->normalize($review,'json',['groups'=>'post:read']);
            return new Response('Suppression effectué avec success'.json_encode($jsonContent));
        }
        return new Response('Error');
    }

    /**
     * @Route("/showRevJson" , name="showRevJson")
     */
    public function allReviewsJson(NormalizerInterface $Normalizer){
        $review =$this->getDoctrine()->getManager()->getRepository(Review::class)->findAll();
        $jsonContent=$Normalizer->normalize($review,'json',['groups'=>'post:read']);

        return new Response(json_encode($jsonContent));
    }




}

templates/front/employes/chefDetail.html.twig
{% extends 'baseFront.html.twig' %}

{% block title %} Profile-Chef{% endblock %}

{% block content %}

    <div class="page-banner-area item-bg4">
        <div class="d-table">
            <div class="d-table-cell">
                <div class="container">
                    <div class="page-banner-content">
                        <h2>Profile Chef</h2>
                        <ul>
                            <li>
                                <a href="{{ path('front') }}">Home</a>
                            </li>
                            <li>Profil Chef</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <section class="services-details-area pt-100 pb-70">
        <div class="container">
            <div class="row">

                <div class="col-lg-8 col-md-12">
                    <div class="services-details-image">
                        <img src="{{ asset('uploads/' ~ chef.file ) }}" alt="image">
                    </div>


                </div>

                <div class="col-lg-4 col-md-12">
                    <div class="services-details-information">


                        <div class="download-file">
                            <h3>Brochures</h3>

                            <ul>
                                <li><a href="#">PDF Download <i class='bx bxs-file-pdf'></i></a></li>
                                <li><a href="#">Services Details.txt <i class='bx bxs-file-txt'></i></a></li>
                            </ul>
                        </div>

                        <div class="services-contact-info">
                            <h3>Contact Info</h3>

                            <ul>
                                <li>
                                    <div class="icon">
                                        <i class='bx bx-user-pin'></i>
                                    </div>
                                    <span>Phone:</span>
                                   {{ chef.phone }}
                                </li>
                                <li>
                                    <div class="icon">
                                        <i class='bx bx-map'></i>
                                    </div>
                                    <span>Location:</span>
                                    {{chef.address }}
                                </li>
                                <li>
                                    <div class="icon">
                                        <i class='bx bx-envelope'></i>
                                    </div>
                                    <span>Email:</span>
                                    {{chef.email}}
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>
{% endblock %}

templates/front/employes/team.html.twig
{% extends 'baseFront.html.twig' %}

{% block title %}Team{% endblock %}

{% block content %}
    <div class="page-banner-area item-bg1">
        <div class="d-table">
            <div class="d-table-cell">
                <div class="container">
                    <div class="page-banner-content">
                        <h2>Team</h2>
                        <ul>
                            <li>
                                <a href="{{ path('front') }}">Home</a>
                            </li>
                            <li>Nos Chefs</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <section class="team-area pt-100 pb-70">

        <div class="container">
            <div class="section-title">
                <h2>Nos Chefs</h2>

                <div class="s-box">
                    <img src="/Front/assets/img/search.svg" class="search-icon">
                    <input type="text" id="search" autocomplete="off" class="s-input">
                    <img  class="vs-icon">
                    <ul class="dropdown" id="entitiesNav"></ul>
                </div>





            </div>

            <div class="row">
                {% for chef in chef %}
                <div class="col-lg-4 col-md-6">

                    <div class="single-team-box">
                        <div class="image">
                            <img class="image" src="{{ asset('uploads/' ~ chef.file ) }}" alt="image" style="width: 500px;height: 300px">

                            <ul class="social">
                                <li>
                                    <a href="{{path('show_chef',{'id':chef.id})}}" target="_blank">
                                        <i class='bx bx-show'></i>
                                    </a>
                                </li>

                            </ul>
                        </div>

                        <div class="content">
                            <h3> {{ chef.nom }} {{ chef.prenom  }}</h3>
                            <span>Chef</span>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </section>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

    <script type="text/javascript">
        jQuery(document).ready(function() {
            var searchRequest = null;
            $("#search").keyup(function() {
                var minlength = 1;
                var that = this;
                var value = $(this).val();
                var entitySelector = $("#entitiesNav").html('');
                if (value.length >= minlength ) {
                    if (searchRequest != null)
                        searchRequest.abort();
                    searchRequest = $.ajax({
                        type: "GET",
                        url: "{{ path('search') }}",
                        data: {
                            'q' : value
                        },
                        dataType: "text",
                        success: function(msg){
                            //we need to check if the value is the same
                            if (value===$(that).val()) {
                                var result = JSON.parse(msg);
                                $.each(result, function(key, arr) {
                                    $.each(arr, function(id, value) {
                                        if (key === 'entities') {
                                            if (id !== 'error') {
                                                entitySelector.append('<li>'+value[1]+'<a href="/show_chef/'+id+'">'+'<img src="/uploads/'+value[0]+'" style="width: 50px; height: 50px; border-radius:50%; "/></a></li>');
                                            } else {
                                                entitySelector.append('<li class="errorLi">'+value+'</li>');
                                            }
                                        }
                                    });
                                });
                            }
                        }
                    });
                }
            });
        });
    </script>

    <style>
        nav {
            display: flex;
            align-items: center;
            justify-content: flex-end;
            margin-right: 30px;
            margin-top: 14px;
        }
        nav a {
            font-size: 13px;
            display: inline-block;
            line-height: 24px;
            font-weight: 400;
            color: rgb(0,0,0,0.87);
            cursor: pointer;
            padding: 5px 6.7px
        }
        nav a:hover {
            text-decoration: underline;
            opacity: .85;
        }
        nav img {
            width: 34px;
            padding: 5px;
            margin: auto 7px;
            cursor: pointer;
        }
        nav img:hover {
            opacity: .8;
        }
        nav button {
            border: 1px solid #4285f4;
            font-weight: bold;
            outline: none;
            background: #4285f4;
            color: #fff;
            padding: 7px 12px;
            border-radius: 3px;
            margin-left: 7px;
            cursor: pointer;
        }
        .section-1 {
            flex: 1;
        }
        .section-1 .logo {
            display: block;
            margin: 0px auto;
            margin-top: 107px;
        }
        .s-box {
            width: 580px;
            margin: 0px auto;
            position: relative;
            margin-top: -8px;
            text-align: center;
        }
        .s-box .s-input {
            display: block;
            border: 1px solid #ddd;
            color: rgba(0,0,0, 0.87);
            font-size: 16px;
            padding: 13px;
            padding-left: 45px;
            border-radius: 25px;
            width: 100%;
            transition: box-shadow 100ms;
            outline: none;
        }
        .s-box  .s-input:focus {
            border: 1px solid #fff;
            border-bottom-left-radius: 0;
            border-bottom-right-radius: 0;
            box-shadow: 0 0 2px rgba(0, 0, 0, 0.05),
            0 0 2px rgba(0, 0, 0, 0.05),
            0 0 3px rgba(0, 0, 0, 0.05),
            0 0 4px rgba(0, 0, 0, 0.05),
            0 0 5px rgba(0, 0, 0, 0.05),
            0 0 4px rgba(0, 0, 0, 0.05),
            0 0 5px rgba(0, 0, 0, 0.05)
        }
        .s-box .search-icon {
            width: 20px;
            opacity: .4;
            position: absolute;
            top: 13px;
            left: 14px;
        }
        .s-box .vs-icon {
            width: 14px;
            position: absolute;
            top: 13px;
            right: 24px;
        }
        .s-btn {
            border: 1px solid transparent;
            padding: 9px 15px;
            color: #666;
            font-size: 14px;
            border-radius: 4px;
            display: inline-block;
            margin-right: 10px;
            margin-top: 28px;
            outline: none;
            cursor: pointer;
            transition: border-color 100ms;
        }
        .s-btn:hover {
            border: 1px solid #aaa;
        }
        .lang {
            margin-top: 30px;
            text-align: center;
            font-size: 13px;
            color: #111;
        }
        .lang a {
            margin-left: 5px;
            color: #1a0dab;
        }
        .lang a:hover {
            text-decoration: underline;
        }


        .links {
            border-top: 1px solid #ddd;
            display: flex;
        }
        .link-1 {
            padding-left: 18.7px;
            flex: 1;
        }
        .link-2 {
            padding-right: 18.7px;
        }

        .entitiesNav {
            display: none;
            background: #fff;
            position: absolute;
            width: 100%;
            top: 47px;
            border-radius: 30px;
            padding: 20px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
            box-shadow: 0 0 2px rgba(0, 0, 0, 0.05),
            0 0 2px rgba(0, 0, 0, 0.05),
            0 0 3px rgba(0, 0, 0, 0.05),
            0 0 4px rgba(0, 0, 0, 0.05),
            0 0 5px rgba(0, 0, 0, 0.05),
            0 0 4px rgba(0, 0, 0, 0.05),
            0 0 5px rgba(0, 0, 0, 0.05)
        }
        .dropdown li {
            list-style: none;
            text-align: left;
        }
        .dropdown li a {
            display: block;
            padding: 8px;
            text-decoration: none;
            color: #222;
            font-size: 18px;
            font-weight: bold;
        }
        .dropdown li a:hover {
            background: #eee;
        }
    </style>
{% endblock%}