src/Entity/Notification.php
<?php

namespace App\Entity;

use App\Repository\NotificationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=NotificationRepository::class)
 */
class Notification
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Message;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Titre;

    /**
     * @ORM\Column(type="integer")
     */
    private $Status;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMessage(): ?string
    {
        return $this->Message;
    }

    public function setMessage(string $Message): self
    {
        $this->Message = $Message;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->Status;
    }

    public function setStatus(int $Status): self
    {
        $this->Status = $Status;

        return $this;
    }
}

src/Controller/BackController.php
<?php

namespace App\Controller;

use App\Repository\EvenementRepository;
use Ob\HighchartsBundle\Highcharts\Highchart;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\UX\Chartjs\Builder\ChartBuilderInterface;
use Symfony\UX\Chartjs\Model\Chart;

class BackController extends AbstractController
{
}

templates/back/Notifications/show.html.twig
{% extends 'baseBack.html.twig' %}
{% block title %}
    Afficher Notification
{% endblock %}
{% block content %}
    <!--start page wrapper -->
    <div class="page-wrapper">
        <div class="page-content">
            <!--breadcrumb-->
            <div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
                <div class="breadcrumb-title pe-3"> Notification </div>
                <div class="ps-3">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb mb-0 p-0">
                            <li class="breadcrumb-item"><a href="javascript:;"><i class="bx bxs-report"></i></a>
                            </li>

                        </ol>
                    </nav>
                </div>

            </div>
            <!--end breadcrumb-->

            </br>
            <h6 class="mb-0 text-uppercase">Liste des Notifications</h6>
            <hr/>
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="table" class="table table-striped table-bordered" style="width:100%">
                            <thead>
                            <tr>
                                <th>Message </th>
                                <th>Titre</th>
                                <th>Etat</th>

                            </tr>
                            </thead>
                            <tbody>
                            {% for notif in notif %}
                                <tr>
                                    <td>{{ notif.message }}</td>
                                    <td>{{ notif.titre }}</td>

                                    <td> {% if notif.Status == 0 %}
                                            <span class="badge bg-light text-white w-100">Unseen</span>
                                        {% else %}
                                            <span class="badge bg-light text-white w-100">Seen</span>
                                        {% endif %}
                                    </td>

                                </tr>
                            {% endfor %}

                            </tbody>
                            <tfoot>
                            <tr>
                            <tr>
                                <th>Message </th>
                                <th>Titre</th>
                                <th>Etat</th>

                            </tr>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>


        </div>
    </div>

    <!--end page wrapper -->
{% endblock %}