src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Serializer\Annotation\Groups;
/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"Username"},message="Username déjà existant !")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("post:read")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Type(type={"alpha", "digit"}, message="Votre nom doit contenir seulement des lettres alphabétiques")
     * @Groups("post:read")
     */

    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Type(type={"alpha", "digit"},message="Votre prénom doit contenir seulement des lettres alphabétiques" )
     * @Groups("post:read")
     */
    private $Prenom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("post:read")
     */
    private $Username;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message=" Email n'est pas valide")
     * @Groups("post:read")
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     * @Groups("post:read")
     */
    private $Roles = [];

    /**
     * @ORM\Column(type="string", length=255)
     *@Assert\Length(
     * min = 8,
     * minMessage = "Votre mot de passe doit contenir au moins 8 caracteres",
     * allowEmptyString = false)
     * @Groups("post:read")
     */
    private $Password;

    /**
     * @Assert\EqualTo(propertyPath ="Password",message="Vous n'avez pas saisi le même mot de passe." )

     */

    private $confirm_password;
    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("post:read")
     */
    private $file;
    /**
     * @ORM\Column(type="datetime")
     * @Groups("post:read")
     */
    private $Created_at;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)

     */
    private $activation_token;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\Length(
     *      min = 8,
     *      max = 8,
     *      minMessage = "Your first name must be at least {{ limit }} characters long",
     *      maxMessage = "Your first name cannot be longer than {{ limit }} characters"
     * )
     * @Groups("post:read")
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups("post:read")
     */
    private $Address;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Groups("post:read")
     */
    private $reset_token;

    /**
     * @ORM\Column(type="integer")
     * @Groups("post:read")
     */
    private $Etat=0;

    /**
     * @ORM\OneToMany(targetEntity=Reclamation::class, mappedBy="user")
     * @ORM\JoinColumn(nullable=false)
     */
    private $reclamations;



    public function __construct()
    {
        $this->reclamations = new ArrayCollection();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->Username;
    }

    public function setUsername(string $Username): self
    {
        $this->Username = $Username;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getRoles(): ?array
    {
        $roles = $this->Roles;
        $roles[] = 'ROLE_USER';
        return array_unique($roles);
    }

    public function setRoles(array $Roles): self
    {
        $this->Roles = $Roles;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->Password;
    }

    public function setPassword(string $Password): self
    {
        $this->Password = $Password;

        return $this;
    }

    public function getFile()
    {
        return $this->file;
    }

    public function setFile($file)
    {
        $this->file = $file;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getConfirmPassword()
    {
        return $this->confirm_password;
    }

    /**
     * @param mixed $confirm_password
     */
    public function setConfirmPassword($confirm_password): void
    {
        $this->confirm_password = $confirm_password;
    }
    public function eraseCredentials() {}
    public function getSalt() {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->Created_at;
    }

    public function setCreatedAt(\DateTimeInterface $Created_at): self
    {
        $this->Created_at = $Created_at;

        return $this;
    }

    public function getActivationToken(): ?string
    {
        return $this->activation_token;
    }

    public function setActivationToken(?string $activation_token): self
    {
        $this->activation_token = $activation_token;

        return $this;
    }

    public function getPhone(): ?int
    {
        return $this->phone;
    }

    public function setPhone(int $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->Address;
    }

    public function setAddress(?string $Address): self
    {
        $this->Address = $Address;

        return $this;
    }

    public function getResetToken(): ?string
    {
        return $this->reset_token;
    }

    public function setResetToken(?string $reset_token): self
    {
        $this->reset_token = $reset_token;

        return $this;
    }

    public function getEtat(): ?int
    {
        return $this->Etat;
    }

    public function setEtat(int $Etat): self
    {
        $this->Etat = $Etat;

        return $this;
    }

    /**
     * @return Collection|Reclamation[]
     */
    public function getReclamations(): Collection
    {
        return $this->reclamations;
    }

    public function addReclamation(Reclamation $reclamation): self
    {
        if (!$this->reclamations->contains($reclamation)) {
            $this->reclamations[] = $reclamation;
            $reclamation->setUser($this);
        }

        return $this;
    }

    public function removeReclamation(Reclamation $reclamation): self
    {
        if ($this->reclamations->removeElement($reclamation)) {
            // set the owning side to null (unless already changed)
            if ($reclamation->getUser() === $this) {
                $reclamation->setUser(null);
            }
        }

        return $this;
    }


}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Reservation;
use App\Entity\Table;
use Captcha\Bundle\CaptchaBundle\Validator\Constraints\ValidCaptcha;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Captcha\Bundle\CaptchaBundle\Form\Type\CaptchaType;



class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom',TextType::class,['label'=>false])
            ->add('datereservation', DateTimeType::class, array(
                'widget' => 'single_text',
                'html5' => true,
                'required' => true,
                'attr' => array('class' => 'form-control input-inline datetimepicker',
                    'data-provide' => 'datetimepicker',
                    'data-format' => 'dd-mm-yyyy HH:ii',
                )))
            ->add('mobile')
            ->add('tableid',EntityType::class ,['class'=>Table::class,
            'choice_label'=>'numerotable'
            ])
            ->add('email',EmailType::class)

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

src/Controller/FrontController.php
<?php

namespace App\Controller;

use App\Entity\Reclamation;
use App\Entity\User;
use App\Entity\Review;
use App\Form\AddReclamationType;
use App\Repository\NotificationRepository;
use App\Repository\ReclamationRepository;
use App\Repository\ReviewRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
class FrontController extends AbstractController
{
    /**
     * @Route("/", name="front")
     */
    public function index(ReviewRepository $repository): Response
    {
        $rev=$repository->findRevMax();
        return $this->render('front/homeFront.html.twig',[
            'rev'=>$rev
        ]);
    }

    /**
     * @return Response
     * @Route("/team",name="team")
     */
    public function afficherChefs(UserRepository $repository){
        $chef=$repository->findChef();
        return $this->render('/front/employes/team.html.twig',[
            'chef'=>$chef
        ]);
    }

    /**
     * @Route("/show_chef/{id}", name="show_chef")
     */
    public function afficherDetailsChef($id,UserRepository $repository){
        $chef=$repository->find($id);
        return $this->render('/front/employes/chefDetail.html.twig',[
            'chef'=>$chef
        ]);
    }

    /**
     * @param Request $request
     * @param UserRepository $repository
     * @Route("/search" , name="search")
     */
    public function search(Request $request,UserRepository $repository){
        $em = $this->getDoctrine()->getManager();

        $requestString = $request->get('q');

        $entities =$repository->findChefByValue($requestString);

        if(!$entities) {
            $result['entities']['error'] = "Aucun chef trouvé";
        } else {
            $result['entities'] = $this->getRealEntities($entities);
        }

        return new Response(json_encode($result));
    }
    public function getRealEntities($entities){

        foreach ($entities as $entity){
            $realEntities[$entity->getId()] =[ $entity->getFile(),$entity->getPrenom()];

        }
        return $realEntities;

    }

    public function showR(ReviewRepository $repository){
        $rev=$repository->findRevMax();
        return $this->render('front/homeFront.html.twig',[
            'rev'=>$rev
        ]);
    }

    /**
     * @return Response
     * @Route("showReview", name="showReview")
     */
    public function showReviews(){

        return $this->render('front/Review/show.html.twig');
    }

    /**
     * @Route("addReview" , name="addReview")
     */
    public function ajouterReview(){
        if(isset($_POST["rating_data"])){
            $Review = new Review();
            $Review->setDescription($_POST["user_review"]);
            $Review->setPublishedAt(new \DateTime('now'));
            $Review->setStars($_POST["rating_data"]);
            $Review->setUserName($_POST["user_name"]);
            $em=$this->getDoctrine()->getManager();
            $em->persist($Review);
            $em->flush();

        }
        return $this->redirectToRoute('showReview');
    }

    /**
     * @param ReviewRepository $repository
     * @return false|string
     * @Route("/calculer", name="calculer")
     */
    public function calculer(ReviewRepository $repository){
        if(isset($_POST["action"])){
            $average_rating = 0;
            $total_review = 0;
            $five_star_review = 0;
            $four_star_review = 0;
            $three_star_review = 0;
            $two_star_review = 0;
            $one_star_review = 0;
            $total_user_rating = 0;
            $review_content = array();
            $result=$repository->findDESC();

            foreach($result as $row)
            {
                $review_content[] = array(
                    'user_name'		=>	$row->getUserName(),
                    'user_review'	=>	$row->getDescription(),
                    'rating'		=>	$row->getStars(),
                    'datetime'		=>	$row->getPublishedAt()
                );

                if($row->getStars() == '5')
                {
                    $five_star_review++;
                }

                if($row->getStars() == '4')
                {
                    $four_star_review++;
                }

                if($row->getStars() == '3')
                {
                    $three_star_review++;
                }

                if($row->getStars() == '2')
                {
                    $two_star_review++;
                }

                if($row->getStars() == '1')
                {
                    $one_star_review++;
                }

                $total_review++;

                $total_user_rating = $total_user_rating + $row->getStars();

            }

            $average_rating = $total_user_rating / $total_review;

            $output = array(
                'average_rating'	=>	number_format($average_rating, 1),
                'total_review'		=>	$total_review,
                'five_star_review'	=>	$five_star_review,
                'four_star_review'	=>	$four_star_review,
                'three_star_review'	=>	$three_star_review,
                'two_star_review'	=>	$two_star_review,
                'one_star_review'	=>	$one_star_review,
                'review_data'		=>	$review_content
            );


        }
        return New Response(json_encode($output));
    }


    ///////////////////////////MOBILE/////////////////////////
    /**
     * @Route("/addRevJson" ,name="addRevJson")
     * @Method ("POST")
     */
    public function addRevJson(Request $request, NormalizerInterface $Normalizer){

        $review =new Review();
        $description = $request->get("description");
        $username= $request->get("user_name");
        $stars=$request->get("stars");

        $review->setStars($stars);
        $review->setDescription($description);
        $review->setUserName($username);
        $review->setPublishedAt(new \DateTime('now'));



        $em=$this->getDoctrine()->getManager();
        $em->persist($review);
        $em->flush();

        $jsonContent=$Normalizer->normalize($review,'json',['groups'=>'post:read']);
        return new Response('Ajout effectué avec success'.json_encode($jsonContent));
    }

    /**
     * @Route("/deleteRevJson/{id}", name="deleteRevJson")
     * @Method ("POST")
     */
    public function deleteReviewJson(Request $request,NormalizerInterface $Normalizer,$id){


        $em=$this->getDoctrine()->getManager();

        $review = $em->getRepository(Review::class)->find($id);
        if($review != null){
            $em->remove( $review);
            $em->flush();


            $jsonContent=$Normalizer->normalize($review,'json',['groups'=>'post:read']);
            return new Response('Suppression effectué avec success'.json_encode($jsonContent));
        }
        return new Response('Error');
    }

    /**
     * @Route("/showRevJson" , name="showRevJson")
     */
    public function allReviewsJson(NormalizerInterface $Normalizer){
        $review =$this->getDoctrine()->getManager()->getRepository(Review::class)->findAll();
        $jsonContent=$Normalizer->normalize($review,'json',['groups'=>'post:read']);

        return new Response(json_encode($jsonContent));
    }




}

templates/front/reservation/index.html.twig
{% extends 'baseFront.html.twig' %}
{% block title %}
    Réservations
{% endblock %}
{% block content %}

    <!-- Start Page Banner -->
    <style>
        .page-banner-area {
            background-image: url(Front/assets/img/h.jpg);
            padding-top: 250px;
        }
    </style>
    <div class="page-banner-area ">
        <div class="d-table">
            <div class="d-table-cell">
                <div class="container">
                    <div class="page-banner-content">
                        <h2>Reservation</h2>
                        <ul>
                            <li>
                                <a href="index.html">Home</a>
                            </li>
                            <li>Reservation</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Page Banner -->

    <!-- Start Checkout Area -->
    <section class="checkout-area ptb-100">
        <div class="container">

            <div class="row">
                <div class="col-lg-6 col-md-12">
                    <div class="billing-details">
                        <h3 class="title">Reservation</h3>


                        {{ form_start(form,{ 'attr' : {'novalidate':'novalidate'} }) }}
                        <div class="row">
                            <div class="col-lg-12 col-md-12">
                                <label for="inputProductDescription" class="form-label">1/ Votre Nom et Prenom</label>
                                {{ form_widget(form.nom,{'attr':{'class':'form-control'}}) }}
                                {{ form_errors(form.nom) }}
                            </div>
                            <div class="col-lg-12 col-md-12">
                                {{ form_label(form.mobile,"2/ votre numero",{'attr':{'class':'form-label'}}) }}
                                {{ form_widget(form.mobile,{'attr':{'class':'form-control'}}) }}
                                {{ form_errors(form.mobile) }}
                            </div>
                            <div class="col-lg-12 col-md-12">
                                {{ form_label(form.datereservation,"3/ date_reservation",{'attr':{'class':'form-label'}}) }}
                                {{ form_widget(form.datereservation)}}
                                {{ form_errors(form.datereservation) }}
                            </div>


                            <div class="col-lg-12 col-md-12">
                                {{ form_label(form.email,"4/ votre email",{'attr':{'class':'form-label'}}) }}
                                {{ form_widget(form.email,{'attr':{'class':'form-control'}}) }}
                                {{ form_errors(form.email) }}
                            </div>
                            <div class="col-lg-12 col-md-12">
                                {{ form_label(form.tableid,"5/ le numero du table",{'attr':{'class':'form-label'}}) }}
                                {{ form_errors(form.tableid) }}
                            </div>
                            <div class="col-lg-12 col-md-12">
                                {{ form_widget(form.tableid,{'attr':{'class':'form-control'}}) }}
                            </div>




                            <button type="submit" class="btn btn-light mx-auto">Reserver</button>

                        </div>
                        {{ form_end (form) }}

                    </div>

                    <div class="col-md-6" >
                        {% if qrcode  %}
                            <img src="{{ qrcode }}" alt="qr-code" >
                        {% endif %}
                    </div>

                </div>

                <div class="col-lg-6 col-md-12">
                    <div class="order-details">
                        <h3 class="title">Table_Disponible</h3>
                        <div class="order-table table-responsive">

                            <table class="table table-bordered">

                                <thead>
                                <tr>
                                    <th scope="col">Numéro</th>
                                    <th scope="col">Image</th>
                                </tr>
                                </thead>
                                <tbody>

                                {% for i in r %}

                                    <tr>
                                        {% if i.etat=='disponible' %}
                                            <td class="product-name">
                                                {{ i.numerotable }}
                                            </td>
                                            <td class="product-total">
                                                <img height="120" width="200" src="{{ asset('uploads/') ~ i.imagetable  }}" alt="image"   >


                                            </td>
                                        {% endif %}
                                    </tr>
                                {% endfor %}



                                </tbody>
                            </table>

                        </div>



                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End Checkout Area -->
{% endblock %}

templates/front/reservation/qrcode.html.twig
<!DOCTYPE html>
<html>

<head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <style type="text/css">
                @media screen {
                        @font-face {
                                font-family: 'Lato';
                                font-style: normal;
                                font-weight: 400;
                                src: local('Lato Regular'), local('Lato-Regular'), url(https://fonts.gstatic.com/s/lato/v11/qIIYRU-oROkIk8vfvxw6QvesZW2xOQ-xsNqO47m55DA.woff) format('woff');
                        }

                        @font-face {
                                font-family: 'Lato';
                                font-style: normal;
                                font-weight: 700;
                                src: local('Lato Bold'), local('Lato-Bold'), url(https://fonts.gstatic.com/s/lato/v11/qdgUG4U09HnJwhYI-uK18wLUuEpTyoUstqEm5AMlJo4.woff) format('woff');
                        }

                        @font-face {
                                font-family: 'Lato';
                                font-style: italic;
                                font-weight: 400;
                                src: local('Lato Italic'), local('Lato-Italic'), url(https://fonts.gstatic.com/s/lato/v11/RYyZNoeFgb0l7W3Vu1aSWOvvDin1pK8aKteLpeZ5c0A.woff) format('woff');
                        }

                        @font-face {
                                font-family: 'Lato';
                                font-style: italic;
                                font-weight: 700;
                                src: local('Lato Bold Italic'), local('Lato-BoldItalic'), url(https://fonts.gstatic.com/s/lato/v11/HkF_qI1x_noxlxhrhMQYELO3LdcAZYWl9Si6vvxL-qU.woff) format('woff');
                        }
                }

                /* CLIENT-SPECIFIC STYLES */
                body,
                table,
                td,
                a {
                        -webkit-text-size-adjust: 100%;
                        -ms-text-size-adjust: 100%;
                }

                table,
                td {
                        mso-table-lspace: 0pt;
                        mso-table-rspace: 0pt;
                }

                img {
                        -ms-interpolation-mode: bicubic;
                }

                /* RESET STYLES */
                img {
                        border: 0;
                        height: auto;
                        line-height: 100%;
                        outline: none;
                        text-decoration: none;
                }

                table {
                        border-collapse: collapse !important;
                }

                body {
                        height: 100% !important;
                        margin: 0 !important;
                        padding: 0 !important;
                        width: 100% !important;
                }

                /* iOS BLUE LINKS */
                a[x-apple-data-detectors] {
                        color: inherit !important;
                        text-decoration: none !important;
                        font-size: inherit !important;
                        font-family: inherit !important;
                        font-weight: inherit !important;
                        line-height: inherit !important;
                }

                /* MOBILE STYLES */
                @media screen and (max-width:600px) {
                        h1 {
                                font-size: 32px !important;
                                line-height: 32px !important;
                        }
                }

                /* ANDROID CENTER FIX */
                div[style*="margin: 16px 0;"] {
                        margin: 0 !important;
                }
        </style>
</head>

<body style="background-color: #f4f4f4; margin: 0 !important; padding: 0 !important;">
<!-- HIDDEN PREHEADER TEXT -->
<div style="display: none; font-size: 1px; color: #fefefe; line-height: 1px; font-family: 'Lato', Helvetica, Arial, sans-serif; max-height: 0px; max-width: 0px; opacity: 0; overflow: hidden;"> We're thrilled to have you here! Get ready to dive into your new account. </div>
<table border="0" cellpadding="0" cellspacing="0" width="100%">
        <!-- LOGO -->
        <tr>
                <td bgcolor="#FFA73B" align="center">
                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
                                <tr>
                                        <td align="center" valign="top" style="padding: 40px 10px 40px 10px;"> </td>
                                </tr>
                        </table>
                </td>
        </tr>
        <tr>
                <td bgcolor="#FFA73B" align="center" style="padding: 0px 10px 0px 10px;">
                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
                                <tr>
                                        <td bgcolor="#ffffff" align="center" valign="top" style="padding: 40px 20px 20px 20px; border-radius: 4px 4px 0px 0px; color: #111111; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 48px; font-weight: 400; letter-spacing: 4px; line-height: 48px;">
                                             <img src="https://i.ibb.co/nLxpyC3/logoo.png" width="125" height="120" style="display: block; border: 0px;" />
                                        </td>
                                </tr>
                        </table>
                </td>
        </tr>
        <tr>
                <td bgcolor="#f4f4f4" align="center" style="padding: 0px 10px 0px 10px;">
                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">

                                <tr>
                                        {% if qrcode  %}
                                                <img src="{{ qrcode }}" alt="qr-code" >
                                        {% endif %}
                                </tr>


                                <tr>
                                        <td bgcolor="#ffffff" align="left" style="padding: 0px 30px 20px 30px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;">
                                                <p style="margin: 0;">Dans ce QR-Code vous devez trouver vos données </p>
                                                <p style="margin: 0;">Merci d'importer avec vous votre QR-Code</p>

                                        </td>
                                </tr>
                                <tr>
                                        <td bgcolor="#ffffff" align="left" style="padding: 0px 30px 40px 30px; border-radius: 0px 0px 4px 4px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;">
                                                <p style="margin: 0;">Bonne Appétit,<br>Foodine Team</p>
                                        </td>
                                </tr>
                        </table>
                </td>
        </tr>

        <tr>
                <td bgcolor="#f4f4f4" align="center" style="padding: 0px 10px 0px 10px;">
                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
                                <tr>
                                        <td bgcolor="#f4f4f4" align="left" style="padding: 0px 30px 30px 30px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; line-height: 18px;"> <br>
                                                <p style="margin: 0;">If these emails get annoying, please feel free to <a href="#" target="_blank" style="color: #111111; font-weight: 700;">unsubscribe</a>.</p>
                                        </td>
                                </tr>
                        </table>
                </td>
        </tr>
</table>
</body>

</html>